Repository zinc-collective/convene, pull requests merged in 2023-07, with the labels that each got.

#1562 🌸✨ `Marketplace`: UI to manage `Order::NotificationMethod`
  app/furniture/marketplace/breadcrumbs.rb
  app/furniture/marketplace/locales/en.yml
  app/furniture/marketplace/management_component.html.erb
  app/furniture/marketplace/marketplace.rb
  app/furniture/marketplace/marketplaces/_form.html.erb
  app/furniture/marketplace/marketplaces/edit.html.erb
  app/furniture/marketplace/notification_method.rb
  app/furniture/marketplace/notification_method_component.html.erb
  app/furniture/marketplace/notification_method_component.rb
  app/furniture/marketplace/notification_method_policy.rb
  app/furniture/marketplace/notification_methods/_form.html.erb
  app/furniture/marketplace/notification_methods/edit.html.erb
  app/furniture/marketplace/notification_methods/index.html.erb
  app/furniture/marketplace/notification_methods/new.html.erb
  app/furniture/marketplace/notification_methods_controller.rb
  app/furniture/marketplace/order/received_mailer.rb
  app/furniture/marketplace/routes.rb
  app/views/application/_email_field.html.erb
  db/migrate/20230615002110_add_marketplace_notification_methods.rb
  db/schema.rb
  spec/factories/furniture/marketplace.rb
  spec/furniture/marketplace/marketplace_spec.rb
  spec/furniture/marketplace/notification_method_spec.rb
  spec/furniture/marketplace/notification_methods_controller_request_spec.rb
  spec/furniture/marketplace/order/received_mailer_spec.rb
  spec/furniture/marketplace/order_notification_method_spec.rb
Labels: ✨ enhancement / use case, 🌸 Gorgeous

#1626 🧹`Marketplace`: Demonstrate usage of `decent_exposure`
  Gemfile
  Gemfile.lock
  app/furniture/marketplace/cart_products_controller.rb
  app/furniture/marketplace/controller.rb
  app/furniture/marketplace/delivery_areas_controller.rb
  app/furniture/marketplace/marketplaces_controller.rb
  app/furniture/marketplace/notification_methods_controller.rb
  app/furniture/marketplace/orders_controller.rb
  app/furniture/marketplace/products_controller.rb
  app/furniture/marketplace/tax_rates_controller.rb
  spec/furniture/marketplace/notification_methods_controller_request_spec.rb
  spec/furniture/marketplace/orders_controller_request_spec.rb
  spec/furniture/marketplace/products_controller_request_spec.rb
Labels: 🧹 refactor

#1642 🌸✨ `Marketplace`: Begin to smooth out Onboarding
  app/furniture/marketplace/locales/en.yml
  app/furniture/marketplace/management_component.html.erb
  app/furniture/marketplace/management_component.rb
  app/furniture/marketplace/marketplace_component.html.erb
  app/furniture/marketplace/marketplace_component.rb
  app/furniture/marketplace/marketplaces/edit.html.erb
  app/furniture/marketplace/onboarding_component.html.erb
  app/furniture/marketplace/onboarding_component.rb
  app/furniture/marketplace/onboarding_component.yml
  spec/factories/furniture/marketplace.rb
  spec/furniture/marketplace/marketplace_component_spec.rb
  spec/furniture/marketplace/onboarding_component_spec.rb
Labels: 🌸 Polish

#1643 🥔✨ `Marketplace`: Check `StripeAccount` when `Onboarding`
  app/furniture/marketplace/locales/en.yml
  app/furniture/marketplace/onboarding_component.html.erb
  app/furniture/marketplace/onboarding_component.rb
  app/furniture/marketplace/onboarding_component.yml
  app/furniture/marketplace/routes.rb
  app/furniture/marketplace/stripe_accounts_controller.rb
  spec/furniture/marketplace/onboarding_component_spec.rb
  spec/furniture/marketplace/stripe_accounts_controller_request_spec.rb
Labels: ✨ enhancement / use case, 🥔 Satisfices

#1648 🥗🧹`Journal`: Make relationships of `Entry` Rails-able
  app/furniture/journal/entry.rb
  spec/furniture/journal/entry_spec.rb
Labels: 🧹 refactor, 🥗 Nutritious

#1633 🥔✨ `Journal`: extract `Term`s from `Entry`s
  app/furniture/journal/entry.rb
  app/furniture/journal/journal.rb
  app/furniture/journal/keyword.rb
  db/migrate/20230704064303_add_journal_keywords.rb
  db/schema.rb
  spec/furniture/journal/entry_spec.rb
  spec/furniture/journal/journal_spec.rb
  spec/furniture/journal/keyword_spec.rb
Labels: ✨ enhancement / use case, 🥔 Satisfices

#1595 🥔✨ `Space`: `Member` may set `Domain`
  app/controllers/spaces_controller.rb
  app/policies/space_policy.rb
  app/views/spaces/_website_settings.html.erb
  spec/requests/spaces_controller_request_spec.rb
Labels: ✨ enhancement / use case, 🥔 Satisfices

#1663 🧹 `Journal`: `Entries` store their `Keywords`
  app/furniture/journal/entry.rb
  app/furniture/journal/keyword.rb
  db/migrate/20230713230334_journal_add_keywords_to_entries.rb
  db/schema.rb
  spec/factories/furniture/journal.rb
  spec/furniture/journal/entry_spec.rb
  spec/furniture/journal/keyword_spec.rb
Labels: 🧹 refactor

#1675 🥗🧹 `Journal`: `Entry` stores each `Keyword` it uses only once.
  app/furniture/journal/entry.rb
  spec/furniture/journal/entry_spec.rb
Labels: 🧹 refactor, 🥗 Nutritious

#1683 🛠️ `Neighborhood`: Bump node to latest v16
  .nvmrc
Labels: 🛠️ infrastructure

#1649 🥔✨ `Journal`: Sprout `Keywords#show`
  app/furniture/journal/entry.rb
  app/furniture/journal/keyword.rb
  app/furniture/journal/keyword_policy.rb
  app/furniture/journal/keywords/show.html.erb
  app/furniture/journal/keywords_controller.rb
  app/furniture/journal/routes.rb
  spec/factories/furniture/journal.rb
  spec/furniture/journal/keywords_controller_request_spec.rb
Labels: ✨ enhancement / use case, 🥔 Satisfices

#1650 🧹 `Journal`: Move `Entry` rendering to `EntryComponent`
  app/furniture/journal/entries/show.html.erb
  app/furniture/journal/entry.rb
  app/furniture/journal/entry_component.html.erb
  app/furniture/journal/entry_component.rb
  app/furniture/journal/journals/_journal.html.erb
  spec/furniture/journal/entry_component_spec.rb
  spec/furniture/journal/entry_spec.rb
Labels: 🧹 refactor

#1684 🥔✨ `Journal`: `Entries` link to their `Keywords`
  app/furniture/journal/entry.rb
  app/furniture/journal/entry_component.rb
  app/furniture/journal/keyword.rb
  spec/furniture/journal/entry_component_spec.rb
  spec/furniture/journal/entry_spec.rb
Labels: ✨ enhancement / use case, 🥔 Satisfices

#1688 🐞🔨 `Marketplace`: `Guest` can see only their `Orders`
  app/furniture/marketplace/order_policy.rb
  app/furniture/marketplace/orders_controller.rb
  spec/furniture/marketplace/order_policy_spec.rb
Labels: 🐞 bug, 🔨 Squashed

#1680 🥗 `Marketplace`: Buying `Products` as a `Guest` System Test
  .env.example
  .github/workflows/test-convene-web.yml
  spec/factories/utility.rb
  spec/furniture/marketplace/buying_products_system_spec.rb
  spec/furniture/marketplace/checkouts_controller_request_spec.rb
  spec/support/stripe_cli.rb
  spec/support/system_helpers.rb
  spec/system/furniture_spec.rb
Labels: 🥗 Nutritious

#1706 🐞🔨 `Marketplace`: Use the default `TimeZone` when showing dates and times
  .env.example
  app/controllers/application_controller.rb
  app/furniture/marketplace/breadcrumbs.rb
  app/furniture/marketplace/orders/_order.html.erb
  app/mailers/application_mailer.rb
  app/models/neighborhood/time_zone_mixin.rb
  config/locales/en.yml
Labels: 🐞 bug, 🔨 Squashed

#1705 🌸 `Marketplace`: Group `Delivery` `Window` and `Address`
  app/furniture/marketplace/cart/deliveries/_delivery.html.erb
  app/furniture/marketplace/carts/_cart.html.erb
Labels: 🌸 Polish

#1703 🐞🔨 `Marketplace`: Only list `paid` `Orders`
  app/furniture/marketplace/orders/index.html.erb
  spec/furniture/marketplace/orders_controller_request_spec.rb
Labels: 🐞 bug, 🔨 Squashed

#1699 🥗🐞🔨 `Marketplace`: Prevent duplicate `Order::Notification`
  app/furniture/marketplace/stripe_events_controller.rb
  spec/furniture/marketplace/stripe_events_controller_request_spec.rb
Labels: 🐞 bug, 🥗 Nutritious, 🔨 Squashed

#1694 🥗 `Marketplace`: Test `Order::Notification` sent `Shopper` and `Vendor`
  .github/workflows/test-convene-web.yml
  spec/factories/furniture/marketplace.rb
  spec/furniture/marketplace/buying_products_system_spec.rb
  spec/support/capybara.rb
  spec/support/stripe_cli.rb
Labels: 🥗 Nutritious

#1701 🧹 `Marketplace`: Cache the fee amount on the `Order`
  app/furniture/marketplace/order.rb
  app/furniture/marketplace/stripe_events_controller.rb
  db/migrate/20230725192832_marketplace_add_payment_processor_fees_to_order.rb
  db/schema.rb
  spec/furniture/marketplace/order_spec.rb
Labels: 🧹 refactor

#1708 🧹 `Journal`: Rename the method that turns Keywords into Links
  app/furniture/journal/entry_component.rb
Labels: 🧹 refactor

#1715 🐞🔨 `Journal`: `Entry` supports overlapping `Keywords`
  app/furniture/journal/entry_component.rb
  app/furniture/journal/keyword.rb
  spec/furniture/journal/entry_component_spec.rb
  spec/furniture/journal/keyword_spec.rb
Labels: 🐞 bug, 🔨 Squashed

#1718 🥔✨`Journal`: Enter `Entry#new` flow via `Keyword#show`
  app/furniture/journal/journals/_journal.html.erb
  app/furniture/journal/keywords/show.html.erb
  app/furniture/journal/locales/en.yml
  app/furniture/journal/new_entry_button_component.html.erb
  app/furniture/journal/new_entry_button_component.rb
Labels: ✨ enhancement / use case, 🥔 Satisfices
