Repository zinc-collective/convene, pull requests merged in 2023-09, with the labels that each got.

#1772 🌸✨ `Marketplace`: Move `Checkout` to it's own page
  app/furniture/marketplace/cart/deliveries/_delivery.html.erb
  app/furniture/marketplace/cart/deliveries/_form.html.erb
  app/furniture/marketplace/cart/deliveries/edit.html.erb
  app/furniture/marketplace/cart/deliveries/show.html.erb
  app/furniture/marketplace/cart/deliveries_controller.rb
  app/furniture/marketplace/cart/delivery_areas/_form.html.erb
  app/furniture/marketplace/carts/_footer.html.erb
  app/furniture/marketplace/checkouts/show.html.erb
  app/furniture/marketplace/checkouts_controller.rb
  app/furniture/marketplace/locales/en.yml
  app/furniture/marketplace/marketplaces/_marketplace.html.erb
  app/furniture/marketplace/marketplaces/edit.html.erb
  app/furniture/marketplace/marketplaces/show.html.erb
  spec/furniture/marketplace/buying_products_system_spec.rb
  spec/furniture/marketplace/cart/deliveries_controller_request_spec.rb
  spec/furniture/marketplace/checkouts_controller_request_spec.rb
Labels: ✨ enhancement / use case, 🌸 Polish

#1825 🥗🐞🔨`Marketplace`: Fix broken Payment Settings page!
  app/furniture/marketplace/stripe_accounts_controller.rb
  spec/furniture/marketplace/collecting_payments_system_spec.rb
Labels: 🐞 bug, 🥗 Nutritious, 🔨 Squashed

#1829 🧹 `Marketplace`: Fix deprecation warning in `Order#price_total`
  app/furniture/marketplace/order.rb
Labels: 🧹 refactor

#1840 🥗🐞🔨 `Marketplace`: Test & Fix Setting `Stripe` API Key
  app/components/button_component.rb
  app/components/marketplace/stripe_overview_component.rb
  app/components/marketplace/stripe_overview_component/stripe_overview_component.html.erb
  app/furniture/marketplace/marketplace.rb
  app/furniture/marketplace/stripe_accounts/show.html.erb
  spec/furniture/marketplace/collecting_payments_system_spec.rb
Labels: 🐞 bug, 🥗 Nutritious, 🔨 Squashed

#1834 🥗 `Marketplace`: Test `Seller` receives `Order` in their `Square` Point of Sale
  app/furniture/marketplace/marketplace.rb
  app/furniture/marketplace/order.rb
  spec/furniture/marketplace/stripe_events_controller_request_spec.rb
Labels: 🥗 Nutritious
