Repository zinc-collective/convene, pull requests merged in 2023-03, with the labels that each got.

#1168 🧹 `Neighborhood`: Update `bundler` gem
  Gemfile.lock
Labels: dependencies, refactor, infrastructure

#1166 🏎️ `Membership`: Find `current_membership` through `Person`, not `Space`
  app/controllers/application_controller.rb
Labels: refactor, performance

#1165 🧹 `Invitation`: Follow `rspec-rails` conventions for Request spec
  spec/requests/rsvps_controller_request_spec.rb
Labels: refactor

#1164 🧹 `Neighborhood`: Respect `pundit`s syntax, `rubocop-rspec`!
  .rubocop.yml
Labels: refactor

#1169 🔐 `Marketplace`: Encrypt `Order#delivery_address`!
  app/furniture/marketplace/cart.rb
  app/furniture/marketplace/order.rb
  db/migrate/20230302202459_marketplace_encrypt_order_delivery_address.rb
  db/schema.rb
  lib/tasks/release.rake
Labels: security, refactor

#1173 ✨ `Marketplace`: Collect `Shopper`s Delivery Address before `Checkout`
  app/furniture/marketplace/cart.rb
  app/furniture/marketplace/cart_policy.rb
  app/furniture/marketplace/carts/_cart.html.erb
  app/furniture/marketplace/carts/_footer.html.erb
  app/furniture/marketplace/carts/_total.html.erb
  app/furniture/marketplace/carts_controller.rb
  app/furniture/marketplace/checkout.rb
  spec/furniture/marketplace/cart_spec.rb
  spec/furniture/marketplace/carts_controller_request_spec.rb
Labels: enhancement

#1172 🐞 `Membership`: `Operator` may create `Invitation`
  app/policies/invitation_policy.rb
  spec/policies/invitation_policy_spec.rb
Labels: 🐞 bug

#1178 🐞 `Space`: `SpacesController#show` works with `BYODomain`
  app/controllers/spaces_controller.rb
  app/views/layouts/application.html.erb
  app/views/spaces/show.html.erb
  spec/rails_helper.rb
  spec/requests/spaces_controller_request_spec.rb
  spec/support/dom_helpers.rb
Labels: 🐞 bug

#1171 🐞 `Space`: Fix broken `SpacesController#new` action
  app/views/spaces/new.html.erb
  spec/requests/spaces_controller_request_spec.rb
  spec/support/auth_helpers.rb
Labels: 🐞 bug

#1181 🧹 `Space`: Use `Space#location` in forms
  app/views/spaces/edit.html.erb
Labels: 🧹 refactor

#1182 🧹 `Room`: Use `Room#location` in form
  app/views/rooms/_form.html.erb
Labels: 🧹 refactor

#1180 🧹 `Furniture`: use `FurniturePlacement#location` in forms
  app/views/furniture_placements/_new.html.erb
Labels: 🧹 refactor

#1179 🧹 `Utility`: Use `UtilityHookup#location` in forms
  app/models/utility_hookup.rb
  app/views/utility_hookups/_form.html.erb
  app/views/utility_hookups/new.html.erb
  config/breadcrumbs.rb
Labels: 🧹 refactor

#1183 🧹 `Rooms`: Get rid of `locked`/`unlocked`/`internal` Rooms in favor of `public`/`internal`
  app/controllers/application_controller.rb
  app/controllers/rooms_controller.rb
  app/controllers/waiting_rooms_controller.rb
  app/helpers/waiting_rooms_helper.rb
  app/javascript/controllers/index.js
  app/javascript/controllers/room_form_controller.js
  app/lib/space_routes.rb
  app/models/blueprint.rb
  app/models/room.rb
  app/models/waiting_room.rb
  app/policies/room_policy.rb
  app/policies/waiting_room_policy.rb
  app/views/rooms/_form.html.erb
  app/views/spaces/_room_card.html.erb
  app/views/waiting_rooms/show.html.erb
  config/breadcrumbs.rb
  config/locales/waiting_room/en.yml
  db/migrate/20230304003325_drop_rooms_access_code.rb
  db/schema.rb
  features/harness/Pages.js
  features/harness/RoomCardComponent.js
  features/harness/RoomEditPage.js
  features/harness/RoomPage.js
  features/harness/WaitingRoomPage.js
  features/lib/AccessCode.js
  features/lib/AccessLevel.js
  features/lib/index.js
  features/rooms.feature
  features/rooms/locking-and-unlocking-rooms.feature
  features/steps/room_steps.js
  features/support/parameter-types/accessCode.js
  features/support/parameter-types/accessLevel.js
  spec/factories/room.rb
  spec/models/blueprint_spec.rb
  spec/models/room_spec.rb
  spec/policies/room_policy_spec.rb
Labels: 🧹 refactor

#1190 🛠️ `Component`: Set up `view_component` `Preview`s
  app/views/layouts/component_preview.html.erb
  config/application.rb
Labels: 🛠️ infrastructure

#1191 🛠️🧹 `Component`: Sprout `CardComponentPreview`
  app/components/application_component.rb
  app/components/card_component.html.erb
  app/components/card_component.rb
  spec/components/previews/card_component_preview.rb
Labels: 🧹 refactor, 🛠️ infrastructure

#1188 🛠️🧹 `Component`s: Make `ButtonComponent` more Customizable
  .rubocop_todo.yml
  app/components/button_component.html.erb
  app/components/button_component.rb
  app/components/icon_button_component.html.erb
  app/furniture/marketplace/products/_product.html.erb
  app/views/furniture_placements/_furniture_placement.html.erb
  app/views/invitations/_invitation.html.erb
  app/views/memberships/_membership.html.erb
  spec/components/button_component_spec.rb
  spec/components/previews/button_component_preview.rb
Labels: 🧹 refactor, 🛠️ infrastructure

#1194 🛠️🌸 `Components`: Install `Lookbook` for Component Preview
  Gemfile
  Gemfile.lock
  config/routes.rb
Labels: 🛠️ infrastructure, 🌸 Gorgeous

#1186 ✨ `Marketplace`: Create and Update `TaxRate`
  app/controllers/application_controller.rb
  app/furniture/marketplace/breadcrumbs.rb
  app/furniture/marketplace/marketplace.rb
  app/furniture/marketplace/marketplaces/edit.html.erb
  app/furniture/marketplace/product.rb
  app/furniture/marketplace/routes.rb
  app/furniture/marketplace/tax_rate.rb
  app/furniture/marketplace/tax_rate_policy.rb
  app/furniture/marketplace/tax_rates/_form.html.erb
  app/furniture/marketplace/tax_rates/_tax_rate.html.erb
  app/furniture/marketplace/tax_rates/edit.html.erb
  app/furniture/marketplace/tax_rates/new.html.erb
  app/furniture/marketplace/tax_rates_controller.rb
  app/views/application/_number_field.html.erb
  db/migrate/20230305005417_create_marketplace_tax_rates.rb
  db/schema.rb
  spec/factories/furniture/marketplace.rb
  spec/furniture/marketplace/tax_rates_controller_request_spec.rb
Labels: ✨ enhancement

#1197 🧹 `Theme`s: Delete the existing implementation
  app/assets/config/manifest.js
  app/controllers/application_controller.rb
  app/models/space.rb
  app/policies/person_policy.rb
  app/policies/space_policy.rb
  app/themes/.gitkeep
  app/themes/desert_dunes/application/_header.html.erb
  app/themes/desert_dunes/layouts/application.html.erb
  app/themes/desert_dunes/styles.css
  app/views/spaces/edit.html.erb
  config/initializers/assets.rb
  config/locales/space/en.yml
  db/migrate/20230307212232_remove_themes_from_spaces.rb
  db/schema.rb
  spec/factories/space.rb
  spec/models/space_spec.rb
  spec/requests/spaces_controller_request_spec.rb
  tailwind.config.cjs
Labels: 🧹 refactor

#1195 🧹🔐🛠️ `Marketplace`: Fully exercise `Policy` objects
  app/furniture/marketplace/cart_policy.rb
  app/furniture/marketplace/cart_product.rb
  app/furniture/marketplace/cart_product_policy.rb
  app/furniture/marketplace/checkout_policy.rb
  app/furniture/marketplace/marketplace_policy.rb
  app/furniture/marketplace/order_policy.rb
  app/furniture/marketplace/policy.rb
  app/furniture/marketplace/product_policy.rb
  app/policies/application_policy.rb
  spec/factories/furniture/marketplace.rb
  spec/factories/marketplace/checkouts.rb
  spec/furniture/marketplace/cart_policy_spec.rb
  spec/furniture/marketplace/cart_product_policy_spec.rb
  spec/furniture/marketplace/checkout_policy_spec.rb
  spec/furniture/marketplace/marketplace_policy_spec.rb
  spec/furniture/marketplace/order_policy_spec.rb
  spec/furniture/marketplace/product_policy_spec.rb
Labels: 🔐 security, 🧹 refactor, 🛠️ infrastructure

#1196 ✨🥔 `Marketplace`: Adding `TaxRate`s to `Product`s
  app/furniture/marketplace/product.rb
  app/furniture/marketplace/product_policy.rb
  app/furniture/marketplace/product_tax_rate.rb
  app/furniture/marketplace/products/_form.html.erb
  app/furniture/marketplace/products/_product.html.erb
  app/furniture/marketplace/products/index.html.erb
  app/furniture/marketplace/tax_rate.rb
  app/views/application/_collection_check_boxes.html.erb
  db/migrate/20230307031329_create_marketplace_product_tax_rates.rb
  db/schema.rb
  spec/furniture/marketplace/products_controller_request_spec.rb
  spec/requests/spaces_controller_request_spec.rb
Labels: ✨ enhancement, 🥔 Satisfices

#1202 🐞 `Marketplace`: catch Stripe errors during account connect and show them to the end user
  app/furniture/marketplace/marketplace.rb
  app/furniture/marketplace/marketplaces/edit.html.erb
  app/furniture/marketplace/stripe_accounts_controller.rb
  spec/furniture/marketplace/stripe_accounts_controller_request_spec.rb
Labels: 🐞 bug

#1203 📝 `Marketplace`: More documentation on getting the `Stripe` Connect flow to work locally.
  app/furniture/marketplace/README.md
Labels: 📝 documentation

#1201 ✨ `Marketplace`: Collect `Order#contact_phone_number` prior to `Checkout`
  app/furniture/marketplace/cart.rb
  app/furniture/marketplace/cart_policy.rb
  app/furniture/marketplace/carts/_cart.html.erb
  app/furniture/marketplace/carts/_footer.html.erb
  app/furniture/marketplace/locales/en.yml
  app/furniture/marketplace/order.rb
  app/furniture/marketplace/order_received_mailer/notification.html.erb
  db/schema.rb
  spec/furniture/marketplace/carts_controller_request_spec.rb
  spec/mailers/previews/marketplace/order_received_mailer_preview.rb
Labels: ✨ enhancement

#1200 ✨`Marketplace`: Collect Taxes for `Product`s with a `TaxRate` on `Checkout`
  app/furniture/marketplace/cart.rb
  app/furniture/marketplace/cart_product.rb
  app/furniture/marketplace/carts/_total.html.erb
  app/furniture/marketplace/checkout.rb
  spec/furniture/marketplace/cart_spec.rb
Labels: ✨ enhancement

#1162 🛠️ `Neighborhood`: Support `bin/erd` and `yarn test` in devcontainer
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/startup.bash
Labels: 🛠️ infrastructure

#1227 🛠️ `Neighborhood`: Send Authorization errors to Sentry
  app/controllers/application_controller.rb
Labels: 🛠️ infrastructure

#1228 ✨ `Marketplace`: `Order#index` is ordered chronologically
  app/furniture/marketplace/orders_controller.rb
Labels: ✨ enhancement

#1232 Set `Order` datetime based off actual order creation
  app/furniture/marketplace/stripe_events_controller.rb
  db/migrate/20230319173737_add_placed_at_to_marketplace_orders.rb
  db/schema.rb
  spec/furniture/marketplace/stripe_events_controller_request_spec.rb
Labels: ✨ enhancement, 🥗 Nutritious

#1231 🥔✨ `Marketplace`: Introduce `TaxRate#index`
  app/furniture/marketplace/breadcrumbs.rb
  app/furniture/marketplace/locales/en.yml
  app/furniture/marketplace/marketplaces/edit.html.erb
  app/furniture/marketplace/tax_rate_component.html.erb
  app/furniture/marketplace/tax_rate_component.rb
  app/furniture/marketplace/tax_rates/index.html.erb
  app/furniture/marketplace/tax_rates_controller.rb
  spec/components/previews/marketplace/tax_rate_component_preview.rb
  spec/furniture/marketplace/tax_rates_controller_request_spec.rb
Labels: ✨ enhancement, 🥔 Satisfices

#1234 ✨🥔 `Marketplace`: `Shopper` sets `Delivery Window`
  app/furniture/marketplace/cart.rb
  app/furniture/marketplace/cart_policy.rb
  app/furniture/marketplace/carts/_cart.html.erb
  app/furniture/marketplace/locales/en.yml
  db/migrate/20230320190449_add_delivery_window_to_marketplace_orders.rb
  db/schema.rb
  spec/furniture/marketplace/carts_controller_request_spec.rb
Labels: ✨ enhancement, 🥔 Satisfices

#1237 ✨🥗 `Marketplace`: `TaxRate#tax_rate` can be set to the 100ths place
  app/furniture/marketplace/tax_rates/_form.html.erb
Labels: ✨ enhancement, 🥗 Nutritious

#1235 ✨🥗 `Marketplace`: Hide `Cart`'s `Checkout` button when empty
  app/furniture/marketplace/cart.rb
  app/furniture/marketplace/cart_product.rb
  app/furniture/marketplace/carts/_footer.html.erb
  spec/factories/furniture/marketplace.rb
Labels: ✨ enhancement, 🥗 Nutritious

#1240 🐞 `Marketplace`: `StripeEvent#create` was failing
  app/furniture/marketplace/stripe_events_controller.rb
  spec/furniture/marketplace/stripe_events_controller_request_spec.rb
Labels: 🐞 bug

#1252 🌸 `Neighborhood`: Tidy up "Account" page
  app/components/card_component.html.erb
  app/views/layouts/_header.html.erb
  app/views/memberships/show.html.erb
  config/locales/invitation/en.yml
Labels: ✨ enhancement, 🌸 Gorgeous

#1253 🌸 `Neighborhood`: Tidy up "New Utility" form and tweak global form styles
  app/assets/stylesheets/components/form.scss
  app/views/application/_password_field.html.erb
  app/views/application/_select.html.erb
  app/views/utilities/new.html.erb
  config/locales/utilities/en.yml
Labels: 🌸 Gorgeous

#1250 🔐 `Marketplace`: Step 3 for Encrypting `Order#contact_email`
  app/furniture/marketplace/cart.rb
  app/furniture/marketplace/order.rb
  db/migrate/20230322235647_drop_marketplace_order_contact_email.rb
  db/schema.rb
Labels: ✨ enhancement, 🔐 security

#1251 🥗 `Marketplace`: Capture `Cart#delivery_window` as a DateTime
  app/furniture/marketplace/cart.rb
  app/furniture/marketplace/carts/_cart.html.erb
  config/locales/en.yml
  spec/furniture/marketplace/carts_controller_request_spec.rb
Labels: ✨ enhancement, 🥗 Nutritious

#1254 🧹 `Furniture`: Add a facility to add attribute-like fields backed by `settings`
  app/furniture/marketplace/marketplace.rb
  app/models/furniture.rb
  spec/models/furniture_spec.rb
Labels: 🧹 refactor

#1259 🧹 `Furniture`: Improve `Furniture#setting` helper, and migrate all Furniture kinds to use it
  app/furniture/embedded_form.rb
  app/furniture/livestream.rb
  app/furniture/markdown_text_block.rb
  app/furniture/marketplace/marketplace.rb
  app/models/furniture.rb
  spec/models/furniture_spec.rb
Labels: 🧹 refactor

#1239 ✨🥔 `Marketplace`: `Shopper` receives `OrderPlaced#notification`
  app/furniture/marketplace/cart.rb
  app/furniture/marketplace/carts/_cart.html.erb
  app/furniture/marketplace/locales/en.yml
  app/furniture/marketplace/order.rb
  app/furniture/marketplace/order_placed_mailer.rb
  app/furniture/marketplace/order_placed_mailer/notification.html.erb
  app/furniture/marketplace/stripe_events_controller.rb
  spec/furniture/marketplace/stripe_events_controller_request_spec.rb
  spec/mailers/previews/marketplace/order_placed_mailer_preview.rb
Labels: ✨ enhancement, 🥔 Satisfices

#1270 🐞 `Marketplace`: `DeliveryWindow` gracefully handles strings
  Gemfile
  Gemfile.lock
  app/furniture/marketplace/cart.rb
  app/furniture/marketplace/carts/_cart.html.erb
  app/furniture/marketplace/marketplace.rb
  app/furniture/marketplace/settings.rb
  app/models/furniture.rb
  app/views/application/_text_field.html.erb
  spec/furniture/marketplace/cart_spec.rb
  spec/furniture/marketplace/marketplace_spec.rb
  spec/furniture/marketplace/marketplaces_controller_request_spec.rb
  spec/rails_helper.rb
Labels: 🐞 bug

#1268 🧹 `Marketplace`: Consolidate Order Emails
  app/furniture/marketplace/locales/en.yml
  app/furniture/marketplace/order.rb
  app/furniture/marketplace/order/email_receipt_component.html.erb
  app/furniture/marketplace/order/email_receipt_component.rb
  app/furniture/marketplace/order/mailer.rb
  app/furniture/marketplace/order/placed_mailer.rb
  app/furniture/marketplace/order/placed_mailer/notification.html.erb
  app/furniture/marketplace/order/received_mailer.rb
  app/furniture/marketplace/order/received_mailer/notification.html.erb
  app/furniture/marketplace/order_placed_mailer.rb
  app/furniture/marketplace/order_placed_mailer/notification.html.erb
  app/furniture/marketplace/order_received_mailer.rb
  app/furniture/marketplace/stripe_events_controller.rb
  spec/factories/furniture/marketplace.rb
  spec/furniture/marketplace/order/placed_mailer_spec.rb
  spec/furniture/marketplace/order/received_mailer_spec.rb
  spec/furniture/marketplace/order_received_mailer_spec.rb
  spec/furniture/marketplace/stripe_events_controller_request_spec.rb
  spec/mailers/previews/marketplace/order/placed_mailer_preview.rb
  spec/mailers/previews/marketplace/order/received_mailer_preview.rb
  spec/mailers/previews/marketplace/order_placed_mailer_preview.rb
  spec/mailers/previews/marketplace/order_received_mailer_preview.rb
  spec/support/i18n.rb
  spec/support/mailer.rb
Labels: 🧹 refactor

#1255 ✨🥔 `Marketplace`: `Distributor` creates `DeliveryArea`
  app/furniture/marketplace/breadcrumbs.rb
  app/furniture/marketplace/delivery_area.rb
  app/furniture/marketplace/delivery_area_policy.rb
  app/furniture/marketplace/delivery_areas/_form.html.erb
  app/furniture/marketplace/delivery_areas/index.html.erb
  app/furniture/marketplace/delivery_areas/new.html.erb
  app/furniture/marketplace/delivery_areas_controller.rb
  app/furniture/marketplace/locales/en.yml
  app/furniture/marketplace/marketplace.rb
  app/furniture/marketplace/routes.rb
  db/migrate/20230323010430_create_marketplace_delivery_areas.rb
  db/schema.rb
  spec/factories/furniture/marketplace.rb
  spec/furniture/marketplace/delivery_areas_controller_request_spec.rb
Labels: 🥔 Satisfices
