Repository zinc-collective/convene, pull requests merged in 2023-08, with the labels that each got.

#1709 🌸`Components`: Remove blank space from `Cards` without `content`
  app/components/card_component.html.erb
  app/components/card_component.rb
  app/furniture/marketplace/management_component.html.erb
  app/furniture/marketplace/tax_rate_component.html.erb
Labels: 🌸 Polish

#1717 🧹 `Marketplace`: Cause Stripe to Retry if we can't mark an `Order` as `paid`
  app/furniture/marketplace/stripe_events_controller.rb
Labels: 🧹 refactor

#1716 ✨ `Journal`: `Entry` can be migrated to another `Journal`
  app/furniture/journal/entry.rb
  spec/furniture/journal/entry_spec.rb
Labels: ✨ enhancement / use case, 🧹 refactor

#1728 🧹 `Marketplace`: Adds Square Ruby SDK gem
  Gemfile
  Gemfile.lock
Labels: 🧹 refactor

#1720 🥗✨ `Journal`: `Keyword`s can be merged into one another
  app/furniture/journal/keyword.rb
  app/furniture/journal/keyword/merge.rb
  spec/furniture/journal/keyword_spec.rb
Labels: ✨ enhancement / use case, 🥗 Nutritious

#1742 🧹 `Neighborhood`: Apparently `MiniTest` is no more
  spec/support/mailer.rb
  spec/support/turbo.rb
Labels: 🧹 refactor

#1712 🌸🥗🥔✨ `Marketplace`: `Orders` expose their `Events`
  app/furniture/marketplace/event_policy.rb
  app/furniture/marketplace/orders/_order.html.erb
  app/furniture/marketplace/orders_controller.rb
  spec/furniture/marketplace/orders_controller_request_spec.rb
Labels: ✨ enhancement / use case, 🥔 Satisfices, 🥗 Nutritious, 🌸 Polish

#1702 🥗🥔✨ `Marketplace`: Failed Automatic `Split` payments try again
  app/furniture/marketplace/split_job.rb
  app/furniture/marketplace/stripe_events_controller.rb
  db/migrate/20230814180326_marketplace_add_stripe_transfer_id_to_orders.rb
  db/schema.rb
  spec/furniture/marketplace/split_job_spec.rb
  spec/furniture/marketplace/stripe_events_controller_request_spec.rb
Labels: ✨ enhancement / use case, 🥔 Satisfices

#1757 🌸✨ `Marketplace`: `Shopper` chooses `DeliveryArea`
  app/furniture/marketplace/breadcrumbs.rb
  app/furniture/marketplace/cart/delivery_area_component.html.erb
  app/furniture/marketplace/cart/delivery_area_component.rb
  app/furniture/marketplace/cart/delivery_areas/_form.html.erb
  app/furniture/marketplace/cart/delivery_areas/edit.html.erb
  app/furniture/marketplace/cart/delivery_areas/show.html.erb
  app/furniture/marketplace/cart/delivery_areas_controller.rb
  app/furniture/marketplace/locales/en.yml
  app/furniture/marketplace/marketplace_component.html.erb
  app/furniture/marketplace/marketplace_component.rb
  app/furniture/marketplace/routes.rb
  app/views/application/_select.html.erb
  spec/furniture/marketplace/buying_products_system_spec.rb
  spec/furniture/marketplace/cart/delivery_areas_controller_request_spec.rb
Labels: 🌸 Polish

#1682 🌸✨ `Marketplace`: `Management` includes ` Payment Settings` screen
  app/components/marketplace/stripe_overview_component.rb
  app/components/marketplace/stripe_overview_component/stripe_overview_component.html.erb
  app/furniture/marketplace/breadcrumbs.rb
  app/furniture/marketplace/locales/en.yml
  app/furniture/marketplace/management_component.html.erb
  app/furniture/marketplace/marketplace.rb
  app/furniture/marketplace/payment_settings/index.html.erb
  app/furniture/marketplace/payment_settings_controller.rb
  app/furniture/marketplace/routes.rb
  spec/components/marketplace/stripe_overview_component_spec.rb
  spec/components/previews/marketplace/stripe_overview_component_preview.rb
Labels: ✨ enhancement / use case, 🌸 Polish

#1792 🛠️✨ `Gizmos`: Support nested layouts
  app/views/layouts/application.html.erb
Labels: ✨ enhancement / use case, 🛠️ infrastructure

#1791 🛠️🔐 `Security`: Review Policy objects and constrain default access levels
  app/policies/invitation_policy.rb
  app/policies/person_policy.rb
  app/policies/rsvp_policy.rb
  spec/policies/invitation_policy_spec.rb
  spec/policies/person_policy_spec.rb
  spec/policies/space_policy_spec.rb
Labels: 🔐 security, 🛠️ infrastructure

#1793 🧹🛠️ `Marketplace`: Wrap the whole thing in Turbo Frames
  app/furniture/layouts/marketplace.html.erb
  app/furniture/marketplace/controller.rb
  app/furniture/marketplace/marketplaces_controller.rb
  app/furniture/marketplace/payment_settings_controller.rb
Labels: 🧹 refactor, 🛠️ infrastructure
