Repository zinc-collective/convene, pull requests merged in 2023-12, with the labels that each got.

#1992 🐞🔨 `Marketplace`: Don't clear `Cart` when switching `Marketplaces`
  app/furniture/marketplace/marketplace_component.rb
  spec/furniture/marketplace/marketplace_component_spec.rb
Labels: 🐞 bug, 🔨 Squashed

#1991 🐞🔨 `Marketplace`: `Checkout` is prevented without a `Cart::DeliveryArea`
  app/furniture/marketplace/cart.rb
  app/furniture/marketplace/carts/_footer.html.erb
  spec/furniture/marketplace/buying_products_system_spec.rb
Labels: 🐞 bug, 🔨 Squashed

#1989 🧹 `Section`: Remove Navigation in favor of `SectionNavigation` Gizmo
  app/furniture/section_navigation/section_navigation.rb
  app/furniture/section_navigation/section_navigations/_section_navigation.html.erb
  app/views/rooms/_room.html.erb
  app/views/spaces/_room_card.html.erb
  features/harness/Components.js
  features/harness/RoomCardComponent.js
  features/harness/RoomFormComponent.js
  features/harness/SpaceEditPage.js
  features/harness/SpacePage.js
  features/rooms/entering-rooms.feature
  features/steps/deployment_steps.js
  features/steps/generic_step.js
  features/steps/identification_steps.js
  features/steps/invitation_steps.js
  features/steps/room_steps.js
  features/steps/space_steps.js
  features/steps/utility_steps.js
  spec/furniture/section_navigation/factories.rb
  spec/furniture/section_navigation/section_navigation_system_spec.rb
Labels: 🧹 refactor

#1982 🧹 `Api`: Use the new, non-deprecated, openapi* methods when initializing RSwag
  config/initializers/rswag-ui.rb
  config/initializers/rswag_api.rb
Labels: 🧹 refactor

#1998 🧹 Remove Hotjar script, extract `<head>` section of layout into shared partial
  app/views/layouts/_head.html.erb
  app/views/layouts/_hotjar.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/minimal.html.erb
Labels: 🐞 bug, 🧹 refactor, 🔨 Squashed

#1999 🌸 `Marketplace`: `Checkout` button is not shown until you can Checkout
  app/furniture/marketplace/carts/_footer.html.erb
Labels: 🌸 Polish

#1936 🥗 `Marketplace`: Test `Seller` receives `Order` in their `Square` Point of Sale
  .github/workflows/test-convene-web.yml
  app/furniture/marketplace/marketplace.rb
  app/furniture/marketplace/orders/index.html.erb
  app/furniture/marketplace/square_idempotency_key.rb
  app/furniture/marketplace/square_order.rb
  app/furniture/marketplace/stripe_events_controller.rb
  spec/factories/furniture/marketplace.rb
  spec/furniture/marketplace/stripe_events_controller_request_spec.rb
  spec/rails_helper.rb
Labels: 🥗 Nutritious

#2007 🧹 Don't encourage people to set the SMTP in .env
  .env.example
Labels: 🧹 refactor

#2006 🐞🔨 `Marketplace`: `Buying Products`: Updating `DeliveryArea` updates `Cart` `DeliveryFee`
  app/furniture/marketplace/cart/delivery_areas/_form.html.erb
  app/furniture/marketplace/cart/delivery_areas_controller.rb
  spec/furniture/marketplace/buying_products_system_spec.rb
  spec/furniture/marketplace/cart/delivery_areas_controller_request_spec.rb
Labels: 🐞 bug, 🔨 Squashed

#2016 🐞🔨 `Neighborhood`: Force full page reload on error page
  app/controllers/application_controller.rb
  app/controllers/errors_controller.rb
  app/views/layouts/_head.html.erb
Labels: 🐞 bug, 🔨 Squashed

#2018 🐞🔨 `Marketplace`: `Flyer` page no longer shows "no content"
  app/furniture/marketplace/flyers/show.html.erb
  spec/furniture/marketplace/flyer_system_spec.rb
Labels: 🐞 bug, 🔨 Squashed

#2015 🐞🔨 `Marketplace`: `DeliveryAreas` cannot be Removed when in use
  app/furniture/marketplace/delivery_area.rb
  app/furniture/marketplace/delivery_area_component.rb
  app/furniture/marketplace/order.rb
  spec/furniture/marketplace/delivery_area_component_spec.rb
  spec/furniture/marketplace/delivery_areas_system_spec.rb
Labels: 🐞 bug, 🔨 Squashed

#2039 🧹 `Marketplace`: Use `unarchive` in favor of `retrieve`
  app/furniture/marketplace/archivable.rb
Labels: 🧹 refactor

#2038 🥗🌸✨ `Marketplace`: Hide `archived` `Products` from `Products#index`
  app/furniture/marketplace/archivable/index_link_component.html.erb
  app/furniture/marketplace/archivable/index_link_component.rb
  app/furniture/marketplace/archivable/index_link_component.yml
  app/furniture/marketplace/component.rb
  app/furniture/marketplace/delivery_areas/index.html.erb
  app/furniture/marketplace/product_component.html.erb
  app/furniture/marketplace/product_component.rb
  app/furniture/marketplace/products/index.html.erb
  spec/furniture/marketplace/archivable/index_link_component_spec.rb
  spec/furniture/marketplace/product_component_spec.rb
  spec/furniture/marketplace/selling_products_system_spec.rb
Labels: ✨ enhancement / use case, 🥗 Nutritious, 🌸 Polish

#2054 🌸 `Marketplace`: All `Member` pages are in the `ManagementComponent`
  app/furniture/layouts/marketplace.html.erb
  app/furniture/marketplace/delivery_areas/edit.html.erb
  app/furniture/marketplace/delivery_areas/index.html.erb
  app/furniture/marketplace/delivery_areas/new.html.erb
  app/furniture/marketplace/marketplaces/edit.html.erb
  app/furniture/marketplace/notification_methods/index.html.erb
  app/furniture/marketplace/payment_settings/index.html.erb
  app/furniture/marketplace/products/edit.html.erb
  app/furniture/marketplace/products/index.html.erb
  app/furniture/marketplace/products/new.html.erb
  app/furniture/marketplace/stripe_accounts/show.html.erb
  app/furniture/marketplace/tax_rates/index.html.erb
Labels: 🌸 Polish

#2058 🐞🔨 `Section`: Permit setting the `#description`
  app/policies/room_policy.rb
  spec/factories/room.rb
  spec/requests/rooms_request_spec.rb
Labels: 🐞 bug, 🔨 Squashed
