Repository zinc-collective/convene, pull requests merged in 2023-05, with the labels that each got.

#1423 🧹 `Marketplace`: return only `Marketplace`s!
  app/furniture/marketplace/marketplace.rb
  spec/furniture/marketplace/marketplace_spec.rb
Labels: 🧹 refactor

#1421 🧹 `Marketplace`: Fix `Faker` deprecation warning
  spec/factories/furniture/marketplace.rb
Labels: 🧹 refactor

#1422 🥗🥔✨🧹 `Marketplace`: `DeliveryConstraint`s only set in `DeliveryArea`
  app/furniture/marketplace/cart.rb
  app/furniture/marketplace/delivery_area.rb
  app/furniture/marketplace/marketplaces/_form.html.erb
  spec/furniture/marketplace/cart_spec.rb
  spec/furniture/marketplace/delivery_area_spec.rb
Labels: ✨ enhancement, 🧹 refactor, 🥔 Satisfices, 🥗 Nutritious

#1420 🥗🧹 `Marketplace`: `Delivery` constraints live on `DeliveryArea`
  app/furniture/marketplace/cart/delivery_expectations_component.rb
  app/furniture/marketplace/checkout.rb
  app/furniture/marketplace/delivery.rb
  app/furniture/marketplace/delivery_area_component.rb
  app/furniture/marketplace/marketplace.rb
  app/furniture/marketplace/order.rb
  docs/erd.png
  spec/factories/furniture/marketplace.rb
  spec/furniture/marketplace/cart/delivery_expectations_component_spec.rb
  spec/furniture/marketplace/cart_spec.rb
  spec/furniture/marketplace/delivery_spec.rb
  spec/furniture/marketplace/marketplaces_controller_request_spec.rb
  spec/furniture/marketplace/order_spec.rb
Labels: 🧹 refactor, 🥗 Nutritious

#1432 🧹🥔✨ `Marketplace`: Move `time_like?` logic for delivery window into presentation layer, remove Window class and type
  app/furniture/marketplace/cart/deliveries/_window_field.html.erb
  app/furniture/marketplace/cart/delivery_expectations_component.html.erb
  app/furniture/marketplace/cart/delivery_expectations_component.rb
  app/furniture/marketplace/cart/delivery_window_component.html.erb
  app/furniture/marketplace/cart/delivery_window_component.rb
  app/furniture/marketplace/delivery/window.rb
  app/furniture/marketplace/delivery/window_type.rb
  app/furniture/marketplace/delivery/windows/_window.html.erb
  app/furniture/marketplace/delivery_area.rb
  app/furniture/marketplace/delivery_area_component.rb
  app/furniture/marketplace/order/email_receipt_component.html.erb
  spec/furniture/marketplace/cart/deliveries_controller_request_spec.rb
  spec/furniture/marketplace/cart/delivery_expectations_component_spec.rb
  spec/furniture/marketplace/cart/delivery_window_component_spec.rb
  spec/furniture/marketplace/delivery/window_spec.rb
  spec/furniture/marketplace/delivery/window_type_spec.rb
  spec/furniture/marketplace/delivery_areas_controller_request_spec.rb
  spec/furniture/marketplace/delivery_spec.rb
  spec/furniture/marketplace/order/email_receipt_component_spec.rb
Labels: ✨ enhancement, 🧹 refactor, 🥔 Satisfices

#1434 🐞 `Marketplace`: Don't explode on `Checkout`
  app/furniture/marketplace/cart.rb
  app/furniture/marketplace/checkout.rb
  app/furniture/marketplace/delivery.rb
  spec/furniture/marketplace/checkout_spec.rb
Labels: 🐞 bug, 🥗 Nutritious

#1440 ✨ `Marketplace`: Display not-ready-for-shopping Marketplace to Space members, with a notice
  app/components/alert_component.html.erb
  app/components/alert_component.rb
  app/components/svg_component.rb
  app/furniture/marketplace/locales/en.yml
  app/furniture/marketplace/marketplaces/_marketplace.html.erb
  spec/components/previews/alert_component_preview.rb
Labels: ✨ enhancement

#1441 🌸✨ `Marketplace`: `Seller` may add `Photo` to `Product`
  Gemfile
  Gemfile.lock
  app/furniture/marketplace/product.rb
  app/furniture/marketplace/product_component.html.erb
  app/furniture/marketplace/product_policy.rb
  app/furniture/marketplace/products/_form.html.erb
  bin/setup
  spec/factories/furniture/marketplace.rb
  spec/fixtures/files/cc-kitten.jpg
Labels: ✨ enhancement, 🌸 Gorgeous

#1444 🥔✨ `Marketplace`: Show `Product::Photo` on `Product` form
  app/furniture/marketplace/products/_form.html.erb
Labels: ✨ enhancement, 🥔 Satisfices

#1445 🥗 `Marketplace`: Test `Products#create` with `Product::Photo`
  spec/factories/furniture/marketplace.rb
  spec/furniture/marketplace/products_controller_request_spec.rb
Labels: 🥗 Nutritious

#1443 🥔✨ `Marketplace`: Show `Product::Photo` in `Cart`
  app/controllers/application_controller.rb
  app/furniture/marketplace/cart_products/_cart_product.html.erb
Labels: ✨ enhancement, 🥔 Satisfices

#1461 🌸 `Spaces`: Prevent Add `Agreement` button from overlapping
  app/assets/stylesheets/base/typography.scss
Labels: 🌸 Gorgeous

#1462 `Marketplace`: `DeliveryArea` and `TaxRate` create buttons should use components
  app/furniture/marketplace/delivery_areas/index.html.erb
  app/furniture/marketplace/tax_rates/index.html.erb
  spec/furniture/marketplace/delivery_areas_controller_request_spec.rb
Labels: 🌸 Gorgeous

#1465 🧹 `Marketplace`: Remove `LockBox.migrate()` from `release.rake`
  lib/tasks/release.rake
Labels: 🔐 security, 🧹 refactor

#1466 🥗✨🧹 `Marketplace`: Every `Marketplace` in a `Space` shares `TaxRate`s
  app/furniture/marketplace/bazaar.rb
  app/furniture/marketplace/controller.rb
  app/furniture/marketplace/management_component.html.erb
  app/furniture/marketplace/marketplace.rb
  app/furniture/marketplace/products/_form.html.erb
  app/furniture/marketplace/tax_rate.rb
  app/furniture/marketplace/tax_rates_controller.rb
  db/migrate/20230514174823_marketplace_add_bazaar_to_tax_rate.rb
  db/schema.rb
  docs/erd.png
  lib/tasks/release.rake
  spec/factories/furniture/marketplace.rb
  spec/furniture/marketplace/bazaar_spec.rb
  spec/furniture/marketplace/tax_rate_spec.rb
  spec/furniture/marketplace/tax_rates_controller_request_spec.rb
Labels: ✨ enhancement, 🧹 refactor, 🥗 Nutritious

#1468 🧹 `Marketplace`: Add Foreign key for `TaxRate#bazaar`
  db/migrate/20230514193224_marketplace_tax_rates_add_foreign_key_to_bazaar_id.rb
  db/migrate/20230514195459_marketplace_tax_rates_validates_bazaar_id_foreign_key.rb
  db/schema.rb
Labels: 🧹 refactor

#1467 🛠️ `Neighborhood`: Microscript to run the changed tests
  bin/test-changed
  bin/test-changed-ruby
Labels: 🛠️ infrastructure

#1476 Replace `Furniture` with `Gizmo`
  app/views/rooms/edit.html.erb
  config/locales/furniture/en.yml
  config/locales/room/en.yml
Labels: 🧹 refactor, 🌸 Gorgeous

#1479 ✨ 🥔 🥗 `Spaces` add Enforce_SSL flag
  db/migrate/20230518014356_add_enforce_ssl_to_spaces.rb
  db/schema.rb
  spec/models/space_spec.rb
Labels: ✨ enhancement, 🥔 Satisfices, 🥗 Nutritious

#1480 `Space`: break up `edit` page into partials, and start unifying it to use Card component for each area
  app/views/spaces/_agreements.html.erb
  app/views/spaces/_people.html.erb
  app/views/spaces/_sections.html.erb
  app/views/spaces/_utilities.html.erb
  app/views/spaces/edit.html.erb
Labels: 🧹 refactor

#1485 🧹 `Neighborhood`: Remove `SystemTest` from First-Run
  app/models/system_test_space.rb
  features/identification.feature
  features/steps/identification_steps.js
  lib/tasks/release.rake
  spec/requests/spaces_controller_request_spec.rb
Labels: 🧹 refactor

#1483 🌸✨ `Members`: `Invitation` email conveys which `Space` and `Person` it came from
  app/mailers/space_invitation_mailer.rb
  app/views/space_invitation_mailer/space_invitation_email.text.erb
  features/lib/Invitation.js
Labels: ✨ enhancement, 🌸 Gorgeous

#1484 ✨ `Space` add "Website Settings" section and enforce ssl checkbox
  app/policies/space_policy.rb
  app/views/spaces/_website_settings.html.erb
  app/views/spaces/edit.html.erb
  config/locales/operator_settings/en.yml
  spec/requests/spaces_controller_request_spec.rb
Labels: ✨ enhancement

#1504 ✨ [#1473] `Space`: redirect Visitors to https if `Space` Enforces SSL
  app/controllers/application_controller.rb
  spec/requests/spaces_controller_request_spec.rb
Labels: ✨ enhancement
