Repository zinc-collective/convene, pull requests merged in 2023-02, with the labels that each got.

#1105 `Neighborhood`: Default to `postgres:latest` image for new databases
  .github/workflows/test-convene-web.yml
  docker-compose.yml
Labels: enhancement

#1104 `Journal`: `Entry`s are paginated
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/furniture/journal.rb
  app/furniture/journal/journals/_journal.html.erb
  app/furniture/journal/routes.rb
  app/helpers/pagy_helper.rb
  config/initializers/pagy.rb
Labels: enhancement

#1092 `Marketplace`: `Vendor` receives `Payment` upon `Order` completion
  app/furniture/marketplace/marketplace.rb
  app/furniture/marketplace/marketplaces/edit.html.erb
  app/furniture/marketplace/routes.rb
  app/furniture/marketplace/stripe_accounts_controller.rb
  app/furniture/marketplace/stripe_events_controller.rb
  app/furniture/marketplace/unexpected_stripe_event_type_error.rb
  spec/factories/furniture/marketplace.rb
  spec/factories/utility_hookup.rb
  spec/furniture/marketplace/checkouts_controller_request_spec.rb
  spec/furniture/marketplace/stripe_accounts_controller_request_spec.rb
  spec/furniture/marketplace/stripe_events_controller_request_spec.rb
  spec/models/utility_hookup_spec.rb
  spec/requests/rooms_request_spec.rb
  spec/requests/utility_hookups_controller_request_spec.rb
Labels: enhancement

#1050 `Neighborhood`: Bump Rails version to patch CVE-2023-22794 and CVE-2023-22797
  Gemfile.lock
Labels: security

#1084 `Neighborhood`: `Operators` may use Github Codespaces for contributing
  .devcontainer/Dockerfile
  .devcontainer/create-db-user.sql
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .devcontainer/startup.bash
  .gitignore
  CONTRIBUTING.md
  docs/devcontainer-usage.md
Labels: enhancement

#1111 `Marketplace`: Allow deletion of `Marketplace`
  app/furniture/furniture.rb
  app/furniture/marketplace/cart.rb
  app/furniture/marketplace/order.rb
  db/migrate/20230210204421_rename_marketplace_carts_and_drop_foreign_key_constraint.rb
  db/schema.rb
  spec/factories/furniture/marketplace.rb
  spec/furniture/marketplace/marketplace_spec.rb
  spec/requests/furniture_placements_controller_request_spec.rb
Labels: bug

#1108 `Marketplace`: notify `Distributor` and `Vendor` of `Order`
  app/controllers/application_controller.rb
  app/furniture/marketplace/marketplace.rb
  app/furniture/marketplace/marketplaces/_form.html.erb
  app/furniture/marketplace/marketplaces_controller.rb
  app/furniture/marketplace/order.rb
  app/furniture/marketplace/order_received_mailer.rb
  app/furniture/marketplace/order_received_mailer/notification.html.erb
  app/furniture/marketplace/stripe_events_controller.rb
  app/mailers/application_mailer.rb
  db/migrate/20230223012939_add_delivery_address_to_marketplace_orders.rb
  db/migrate/20230223015357_add_contact_email_to_marketplace_orders.rb
  db/schema.rb
  spec/factories/furniture/marketplace.rb
  spec/furniture/marketplace/cart_spec.rb
  spec/furniture/marketplace/order_received_mailer_spec.rb
  spec/furniture/marketplace/stripe_events_controller_request_spec.rb
  spec/mailers/previews/marketplace/order_received_mailer_preview.rb
Labels: enhancement

#1142 `Refactor`: Extract `CardComponent` and unwind bad scss
  app/assets/stylesheets/components.scss
  app/assets/stylesheets/components/guide_summary.scss
  app/assets/stylesheets/components/room_card.scss
  app/assets/stylesheets/utilities.scss
  app/assets/stylesheets/utilities/card.scss
  app/components/card_component.html.erb
  app/components/card_component.rb
  app/views/spaces/_room_card.html.erb
  features/harness/RoomCardComponent.js
Labels: refactor

#1146 `Refactor`: Delete `Guide`s
  app/assets/stylesheets/components.scss
  app/assets/stylesheets/components/guide_summary.scss
  app/controllers/guides_controller.rb
  app/models/guide.rb
  app/views/guides/_furniture.md
  app/views/guides/_getting_around.md
  app/views/guides/_glossary.md
  app/views/guides/_identification.md
  app/views/guides/_neighborhoods.md
  app/views/guides/_people.md
  app/views/guides/_rooms.md
  app/views/guides/_service_hookups.md
  app/views/guides/_spaces.md
  app/views/guides/index.html.erb
  app/views/guides/show.html.erb
  config/breadcrumbs.rb
  config/initializers/markdown_templates.rb
  config/locales/en.yml
  config/routes.rb
Labels: refactor

#1140 `Dev`: Install Solargraph on DevContainer
  .devcontainer/devcontainer.json
Labels: refactor
