Repository zinc-collective/convene, pull requests merged in 2023-06, with the labels that each got.

#1519 🥗🔨🐞 `Neighborhood`: Footer links to the Neighborhood URL
  app/components/neighborhood/link_component.rb
  app/models/neighborhood.rb
  app/views/layouts/application.html.erb
  spec/components/neighborhood/link_component_spec.rb
Labels: 🐞 bug, 🥗 Nutritious, 🔨 Squashed

#1517 🌸 `Marketplace`: `Product::Photos` don't reflow the page
  app/furniture/marketplace/cart_product_component.html.erb
Labels: 🌸 Gorgeous

#1521 📝 `Contributors`: Revise `CONTRIBUTING.md`
  .vscode/ltex.dictionary.en-US.txt
  CONTRIBUTING.md
  docs/convene-architecture-overview.jpg
Labels: 📝 documentation

#1563 📝 `Neighborhood`: Document how an `Operator` adds a `Space`
  README.md
  docs/operator.md
Labels: 📝 documentation

#1583 `Journal`: Add `New Entry` button to the top of the `Journal` view
  app/furniture/journal/journals/_journal.html.erb
Labels: ✨ enhancement

#1594 🧹 `Neighborhood`: Get rid of unused `Feature` model
  .env.example
  app.json
  app/models/feature.rb
  spec/models/feature_spec.rb
Labels: 🧹 refactor

#1596 ✨🥔 `Components`: Expose `ButtonComponent#danger` variant
  app/components/button_component.rb
  spec/components/button_component_spec.rb
Labels: ✨ enhancement

#1593 ✨`Space`: Prompt to add `Gizmo` to `Entrance`
  app/views/spaces/edit.html.erb
  config/locales/space/en.yml
Labels: ✨ enhancement, 🥔 Satisfices

#1598 🧹 `Gizmo`: Access a `Room`'s Gizmos via `.gizmos`
  app/controllers/application_controller.rb
  app/controllers/furnitures_controller.rb
  app/furniture/embedded_forms/_form.html.erb
  app/furniture/livestreams/_form.html.erb
  app/furniture/markdown_text_blocks/_form.html.erb
  app/furniture/marketplace/bazaar.rb
  app/furniture/marketplace/marketplace.rb
  app/models/blueprint.rb
  app/models/furniture.rb
  app/models/room.rb
  app/models/room/serializer.rb
  app/models/space.rb
  app/policies/furniture_policy.rb
  app/policies/room_policy.rb
  app/views/furnitures/_new.html.erb
  app/views/furnitures/create.turbo_stream.erb
  app/views/rooms/_room.html.erb
  app/views/rooms/edit.html.erb
  app/views/spaces/edit.html.erb
  features/lib/Room.js
  features/steps/furniture_steps.js
  spec/models/blueprint_spec.rb
  spec/models/furniture_spec.rb
  spec/models/room_spec.rb
  spec/models/space_spec.rb
  spec/requests/furnitures_controller_request_spec.rb
  spec/requests/rooms_request_spec.rb
Labels: 🧹 refactor

#1614 🌸✨ `Component`: Add `bell` option to `SvgComponent`
  app/components/svg_component.rb
Labels: ✨ enhancement / use case, 🌸 Gorgeous

#1619 Remove lingering obsolete references to video spaces
  CONTRIBUTING.md
  app/controllers/application_controller.rb
Labels: 🧹 refactor
