Repository zinc-collective/convene, pull requests merged in 2023-04, with the labels that each got.

#1300 🐛🔨 `Neighborhood`: Update Room policy scope to not show inaccessible rooms to users
  .rubocop_todo.yml
  app/models/room.rb
  app/policies/room_policy.rb
  spec/furniture/marketplace/stripe_accounts_controller_request_spec.rb
  spec/furniture/marketplace/stripe_events_controller_request_spec.rb
  spec/models/room_spec.rb
  spec/policies/room_policy_spec.rb
Labels: 🐞 bug, 🔐 security

#1298 🛠️🧹🥗 `Neighborhood`: `WithinLocation` supports routing to singular resources
  app/furniture/journal/entry.rb
  app/furniture/journal/journal.rb
  app/furniture/markdown_text_block.rb
  app/furniture/marketplace/cart.rb
  app/furniture/marketplace/checkout.rb
  app/furniture/marketplace/delivery_area.rb
  app/furniture/marketplace/marketplace.rb
  app/furniture/marketplace/order.rb
  app/furniture/marketplace/ordered_product.rb
  app/furniture/marketplace/product.rb
  app/furniture/marketplace/tax_rate.rb
  app/models/furniture.rb
  app/models/invitation.rb
  app/models/room.rb
  app/models/rsvp.rb
  app/models/space.rb
  app/models/within_location.rb
  spec/models/within_location_spec.rb
Labels: 🧹 refactor, 🛠️ infrastructure, 🥗 Nutritious

#1307 🐞🔨 `Marketplace`: Stop dropping `Order#contact_email`
  app/furniture/marketplace/cart.rb
  app/furniture/marketplace/marketplaces/_marketplace.html.erb
  app/furniture/marketplace/order.rb
Labels: 🐞 bug

#1318 🥗 `Marketplace`: Destroy `DeliveryArea` when destroying `Marketplace`
  app/furniture/marketplace/marketplace.rb
  spec/furniture/marketplace/marketplace_spec.rb
Labels: 🥗 Nutritious

#1319 🧹🔨🥗`Marketplace`: Show `Order#delivery_window` in `Order::EmailReceiptComponent`
  Gemfile
  Gemfile.lock
  app/furniture/marketplace/cart.rb
  app/furniture/marketplace/cart/deliveries/_form.html.erb
  app/furniture/marketplace/cart/deliveries/_window_field.html.erb
  app/furniture/marketplace/cart/delivery.rb
  app/furniture/marketplace/carts/_cart.html.erb
  app/furniture/marketplace/delivery.rb
  app/furniture/marketplace/delivery/window.rb
  app/furniture/marketplace/delivery/window_type.rb
  app/furniture/marketplace/delivery/windows/_window.html.erb
  app/furniture/marketplace/marketplaces/_marketplace.html.erb
  app/furniture/marketplace/order.rb
  app/furniture/marketplace/order/email_receipt_component.html.erb
  app/views/application/_datetime_field.html.erb
  docs/erd.png
  spec/factories/furniture/marketplace.rb
  spec/furniture/marketplace/cart/deliveries_controller_request_spec.rb
  spec/furniture/marketplace/delivery/window_spec.rb
  spec/furniture/marketplace/delivery/window_type_spec.rb
  spec/furniture/marketplace/delivery_spec.rb
  spec/furniture/marketplace/order/email_receipt_component_spec.rb
  spec/support/view_component.rb
Labels: ✨ enhancement, 🛠️ infrastructure, 🥗 Nutritious

#1328 🧹🥔✨ `Utilities`: Tidy up `#edit` and `#destroy` use-cases
  app/controllers/utilities_controller.rb
  app/views/spaces/edit.html.erb
  app/views/utilities/_form.html.erb
  app/views/utilities/edit.html.erb
  config/breadcrumbs.rb
  config/locales/icon/en.yml
  config/locales/utilities/en.yml
  spec/requests/utilities_controller_request_spec.rb
Labels: ✨ enhancement, 🧹 refactor, 🥔 Satisfices

#1322 🌸🥔✨ `Marketplace`: `Shopper` chooses `DeliveryArea` for their `Order`
  app/furniture/marketplace/cart/deliveries/_delivery.html.erb
  app/furniture/marketplace/cart/deliveries/_form.html.erb
  app/furniture/marketplace/cart/delivery.rb
  app/furniture/marketplace/cart/delivery/edit_button_component.rb
  app/furniture/marketplace/cart/delivery_policy.rb
  app/furniture/marketplace/delivery_areas/_delivery_area.html.erb
  db/migrate/20230408033925_carts_have_delivery_area.rb
  db/schema.rb
  spec/factories/furniture/marketplace.rb
  spec/furniture/marketplace/cart/deliveries_controller_request_spec.rb
  spec/furniture/marketplace/cart/delivery_policy_spec.rb
  spec/furniture/marketplace/cart/delivery_spec.rb
Labels: ✨ enhancement, 🥔 Satisfices, 🌸 Gorgeous

#1323 🧹🥗🥔 `Marketplace`: Use `DeliveryArea#price` to calculate `Cart#price_total`
  app/furniture/marketplace/cart.rb
  app/furniture/marketplace/cart/delivery.rb
  app/furniture/marketplace/delivery.rb
  spec/factories/furniture/marketplace.rb
  spec/furniture/marketplace/cart_spec.rb
  spec/furniture/marketplace/delivery_spec.rb
Labels: ✨ enhancement, 🧹 refactor, 🥔 Satisfices, 🥗 Nutritious

#1332 🥗🧹🥔✨ `Marketplace`: Show `DeliveryArea` in `Order::EmailReceiptComponent`
  app/furniture/marketplace/delivery_area.rb
  app/furniture/marketplace/order.rb
  app/furniture/marketplace/order/email_receipt_component.html.erb
  spec/factories/furniture/marketplace.rb
  spec/furniture/marketplace/delivery_area_spec.rb
  spec/furniture/marketplace/delivery_spec.rb
  spec/furniture/marketplace/order/email_receipt_component_spec.rb
  spec/furniture/marketplace/order_spec.rb
Labels: ✨ enhancement, 🧹 refactor, 🥔 Satisfices, 🥗 Nutritious

#1333 🌸 `Components`: Reduce `Card` padding on small screens
  app/components/card_component.html.erb
  tailwind.config.cjs
Labels: 🌸 Gorgeous

#1334 🌸 `Marketplace`: Tidy up `Order#show` and `Order#index`
  app/furniture/marketplace/orders/_order.html.erb
  app/furniture/marketplace/orders/index.html.erb
  app/furniture/marketplace/orders/show.html.erb
Labels: 🌸 Gorgeous

#1335 🛠️ `Neighborhood`: Add error field workaround to display association errors correctly on forms
  app/furniture/marketplace/delivery.rb
  app/furniture/marketplace/locales/en.yml
  app/views/application/_error.html.erb
  spec/furniture/marketplace/cart/delivery_spec.rb
Labels: 🧹 refactor

#1337 🧹🐞🌸 `Marketplace`: Tidy up `Product#index`
  app/components/application_component.rb
  app/furniture/marketplace/breadcrumbs.rb
  app/furniture/marketplace/locales/en.yml
  app/furniture/marketplace/products/_product.html.erb
  app/furniture/marketplace/products/index.html.erb
  app/furniture/marketplace/products/new.html.erb
  app/furniture/marketplace/products_controller.rb
  app/furniture/marketplace/tax_rates/_tax_rate.html.erb
  app/views/buttons/_edit.html.erb
  app/views/buttons/_new.html.erb
  spec/furniture/marketplace/products_controller_request_spec.rb
Labels: 🐞 bug, 🧹 refactor, 🌸 Gorgeous

#1341 🛠️ `Components`: Tailwind Look for classes in `Furniture`
  tailwind.config.cjs
Labels: 🛠️ infrastructure

#1339 🛠️ `Neighborhood`: Enforce `rubocop-capybara` and quiet the notice
  .rubocop.yml
Labels: 🛠️ infrastructure

#1340 🌸`Marketplace`: Bring `Product` and `TaxRate` UI closer
  app/furniture/marketplace/locales/en.yml
  app/furniture/marketplace/products/_form.html.erb
  app/furniture/marketplace/products/_product.html.erb
  app/furniture/marketplace/products/index.html.erb
  config/locales/en.yml
Labels: 🌸 Gorgeous

#1343 🛠️ `Component`s: `spec`s with `type: :component` support `polymorphic_path`
  spec/support/view_component.rb
Labels: 🛠️ infrastructure

#1342 🛠️🥗 `Components`: expose `policy` method
  app/components/application_component.rb
  app/policies/application_policy.rb
  spec/components/application_component_spec.rb
Labels: 🛠️ infrastructure, 🥗 Nutritious

#1344 🥗🛠️ `Marketplace`: Add associations and validations to `TaxRate`
  app/furniture/marketplace/tax_rate.rb
  app/furniture/marketplace/tax_rate_policy.rb
  spec/furniture/marketplace/tax_rate_spec.rb
Labels: 🛠️ infrastructure, 🥗 Nutritious

#1303 ✨🥔 `Marketplace`: `Distributor` edits `DeliveryArea`
  app/furniture/marketplace/breadcrumbs.rb
  app/furniture/marketplace/delivery_area_policy.rb
  app/furniture/marketplace/delivery_areas/edit.html.erb
  app/furniture/marketplace/delivery_areas/index.html.erb
  app/furniture/marketplace/delivery_areas_controller.rb
  spec/furniture/marketplace/delivery_areas_controller_request_spec.rb
Labels: ✨ enhancement, 🥔 Satisfices, 🥗 Nutritious

#1347 ✨🥗 `Marketplace`: `TaxRate` actions support Turbo
  app/furniture/marketplace/tax_rates_controller.rb
  spec/furniture/marketplace/tax_rates_controller_request_spec.rb
Labels: ✨ enhancement, 🥗 Nutritious

#1338 🌸🥗✨ `Marketplace`: Tidy up managing `TaxRate`s
  app/furniture/marketplace/locales/en.yml
  app/furniture/marketplace/tax_rate_component.html.erb
  app/furniture/marketplace/tax_rate_component.rb
  app/furniture/marketplace/tax_rates/_form.html.erb
  app/furniture/marketplace/tax_rates/index.html.erb
  spec/components/previews/marketplace/tax_rate_component_preview.rb
  spec/factories/furniture/marketplace.rb
  spec/furniture/marketplace/tax_rate_component_spec.rb
Labels: ✨ enhancement, 🥗 Nutritious, 🌸 Gorgeous

#1348 🛠️ `Components`: Create simple `SvgComponent`, and add a reusable `Gear` icon component
  app/components/application_component.rb
  app/components/icons/gear_component.rb
  app/components/svg_component.rb
  app/views/application/_breadcrumbs.html.erb
  app/views/spaces/_room_card.html.erb
Labels: 🛠️ infrastructure

#1329 🌸✨ `Marketplace`: Add shared Marketplace Management component
  app/components/button_component.rb
  app/components/buttons/secondary_component.rb
  app/furniture/marketplace/cart/deliveries/_delivery.html.erb
  app/furniture/marketplace/cart/delivery/edit_button_component.rb
  app/furniture/marketplace/delivery_areas/index.html.erb
  app/furniture/marketplace/locales/en.yml
  app/furniture/marketplace/management_component.html.erb
  app/furniture/marketplace/management_component.rb
  app/furniture/marketplace/management_menu_item_component.html.erb
  app/furniture/marketplace/management_menu_item_component.rb
  app/furniture/marketplace/marketplaces/_marketplace.html.erb
  app/furniture/marketplace/marketplaces/edit.html.erb
  app/furniture/marketplace/orders/_order.html.erb
  app/furniture/marketplace/products/_product.html.erb
  app/furniture/marketplace/products/index.html.erb
  app/furniture/marketplace/tax_rates/index.html.erb
  app/views/furnitures/_furniture.html.erb
  app/views/invitations/_invitation.html.erb
  app/views/memberships/_membership.html.erb
  app/views/spaces/edit.html.erb
  spec/components/previews/button_component_preview.rb
  spec/components/previews/buttons/secondary_component_preview.rb
Labels: ✨ enhancement, 🌸 Gorgeous

#1354 🛠 `Neighborhood`: Adds strong_migrations gem
  Gemfile
  Gemfile.lock
  config/initializers/strong_migrations.rb
Labels: 🛠️ infrastructure

#1355 🥗🥔✨ `Marketplace`: `Distributor` deletes a `DeliveryArea`
  app/furniture/marketplace/delivery_area_component.html.erb
  app/furniture/marketplace/delivery_area_component.rb
  app/furniture/marketplace/delivery_areas/index.html.erb
  app/furniture/marketplace/delivery_areas_controller.rb
  app/furniture/marketplace/locales/en.yml
  config/locales/en.yml
  spec/furniture/marketplace/delivery_areas_controller_request_spec.rb
Labels: ✨ enhancement, 🥔 Satisfices, 🥗 Nutritious

#1357 🌸✨ `Marketplace`: Require confirmation before deleting `Product`s and `TaxRate`s
  app/furniture/marketplace/products/_product.html.erb
  app/furniture/marketplace/tax_rate_component.rb
Labels: ✨ enhancement, 🌸 Gorgeous

#1351 🛠️📝 `Neighborhood`: Don't reference PostgreSQL 12 specifically
  CONTRIBUTING.md
Labels: 🛠️ infrastructure, 📝 documentation

#1352 🧹`Marketplace`: Remove unused `TaxRate` partial!
  app/furniture/marketplace/tax_rates/_tax_rate.html.erb
  spec/support/turbo.rb
Labels: 🧹 refactor

#1358 🧹`Components`: Pull `edit_button` up into `ApplicationComponent`
  app/components/application_component.rb
  app/furniture/marketplace/delivery_area_component.rb
  app/furniture/marketplace/tax_rate_component.rb
Labels: 🧹 refactor

#1359 🧹 `Marketplace` `management` component cleanups
  app/components/buttons/secondary_component.rb
  app/furniture/marketplace/delivery_areas/index.html.erb
  app/furniture/marketplace/locales/en.yml
  app/furniture/marketplace/management_component.html.erb
  app/furniture/marketplace/management_component.rb
Labels: 🧹 refactor

#1363 🧹 `Space`: `Invitation`s request spec lives where it should
  .rubocop_todo.yml
  spec/requests/invitations_controller_request_spec.rb
Labels: 🧹 refactor

#1365 ✨🥔 `Agreement`: They can be shown!
  app/controllers/space/agreements_controller.rb
  app/lib/space_routes.rb
  app/models/space/agreement.rb
  app/policies/space/agreement_policy.rb
  app/views/space/agreements/_agreement.html.erb
  app/views/space/agreements/show.html.erb
  config/breadcrumbs.rb
  config/locales/en.yml
  spec/requests/space/agreements_controller_request_spec.rb
Labels: ✨ enhancement, 🥔 Satisfices

#1367 🥔✨ `Agreements`: List `Agremeent`s on `Space#edit`
  app/views/spaces/edit.html.erb
  config/locales/agreement/en.yml
Labels: ✨ enhancement, 🥔 Satisfices

#1370 🧹`Components`: add Svg `icon` variants and Button `scheme`s
  app/components/application_component.rb
  app/components/button_component.rb
  app/components/buttons/secondary_component.rb
  app/components/icons/gear_component.rb
  app/components/svg_component.rb
  app/furniture/marketplace/cart/deliveries/_delivery.html.erb
  app/furniture/marketplace/delivery_area_component.rb
  app/furniture/marketplace/management_component.html.erb
  app/furniture/marketplace/management_menu_item_component.rb
  app/furniture/marketplace/marketplaces/_marketplace.html.erb
  app/furniture/marketplace/marketplaces/edit.html.erb
  app/furniture/marketplace/product_component.rb
  app/furniture/marketplace/products/index.html.erb
  app/furniture/marketplace/tax_rate_component.rb
  app/views/application/_breadcrumbs.html.erb
  app/views/furnitures/_furniture.html.erb
  app/views/invitations/_invitation.html.erb
  app/views/memberships/_membership.html.erb
  app/views/spaces/edit.html.erb
  spec/components/previews/button_component_preview.rb
  spec/components/previews/buttons/secondary_component_preview.rb
  tailwind.config.cjs
Labels: 🧹 refactor

#1373 🥗🥔🧹✨ `Marketplace`: Test how we communicate `DeliveryExpectations`
  app/furniture/marketplace/cart/delivery_expectations_component.html.erb
  app/furniture/marketplace/cart/delivery_expectations_component.rb
  app/furniture/marketplace/carts/_cart.html.erb
  config/locales/en.yml
  spec/furniture/marketplace/cart/delivery_expectations_component_spec.rb
Labels: ✨ enhancement, 🧹 refactor, 🥔 Satisfices, 🥗 Nutritious

#1372 🥗🥔✨ `Marketplace`: Show `DeliveryArea`'s `#order_by` and `#delivery_window`
  app/furniture/marketplace/delivery/windows/_window.html.erb
  app/furniture/marketplace/delivery_area_component.html.erb
  app/furniture/marketplace/delivery_area_component.rb
  spec/factories/furniture/marketplace.rb
  spec/furniture/marketplace/delivery_area_component_spec.rb
Labels: ✨ enhancement, 🥔 Satisfices, 🥗 Nutritious

#1371 🥗🥔✨ `Marketplace`: add `order_by` and `delivery_window` to `DeliveryArea`
  app/furniture/marketplace/delivery/windows/_window.html.erb
  app/furniture/marketplace/delivery_area_component.html.erb
  app/furniture/marketplace/delivery_area_component.rb
  app/furniture/marketplace/delivery_area_policy.rb
  app/furniture/marketplace/delivery_areas/_form.html.erb
  app/furniture/marketplace/delivery_areas_controller.rb
  app/furniture/marketplace/locales/en.yml
  db/migrate/20230416172045_add_order_by_and_delivery_window_to_marketplace_delivery_areas.rb
  db/schema.rb
  spec/factories/furniture/marketplace.rb
  spec/furniture/marketplace/delivery_area_component_spec.rb
  spec/furniture/marketplace/delivery_areas_controller_request_spec.rb
Labels: ✨ enhancement, 🥔 Satisfices, 🥗 Nutritious

#1378 🥗 `Marketplace`: Woops, both `Delivery` patches worked independently...
  app/furniture/marketplace/cart/delivery_expectations_component.html.erb
  app/furniture/marketplace/cart/delivery_expectations_component.rb
  app/furniture/marketplace/delivery/windows/_window.html.erb
  app/furniture/marketplace/delivery_area_component.html.erb
  app/furniture/marketplace/delivery_area_component.rb
  spec/furniture/marketplace/delivery_area_component_spec.rb
Labels: 🥗 Nutritious

#1377 🧹 `Agreements`: Add some quotes get rid of weird
  app/controllers/space/agreements_controller.rb
  config/locales/agreement/en.yml
Labels: 🧹 refactor

#1376 🥗🥔✨`Agreements`: Can be destroyed!
  app/controllers/space/agreements_controller.rb
  app/lib/space_routes.rb
  app/policies/space/agreement_policy.rb
  app/views/spaces/edit.html.erb
  config/locales/agreement/en.yml
  spec/requests/space/agreements_controller_request_spec.rb
Labels: ✨ enhancement, 🥔 Satisfices, 🥗 Nutritious

#1379 🥗🥔✨ `Agreements`: Tee up the `#update` action
  app/controllers/space/agreements_controller.rb
  app/lib/space_routes.rb
  app/policies/space/agreement_policy.rb
  app/views/space/agreements/edit.html.erb
  config/locales/agreement/en.yml
  spec/requests/space/agreements_controller_request_spec.rb
Labels: ✨ enhancement, 🥔 Satisfices, 🥗 Nutritious

#1380 🥗🥔✨ `Agreements`: Can be edited!
  app/controllers/space/agreements_controller.rb
  app/lib/space_routes.rb
  app/views/space/agreements/_form.html.erb
  app/views/space/agreements/edit.html.erb
  app/views/space/agreements/new.html.erb
  app/views/spaces/edit.html.erb
  config/breadcrumbs.rb
  config/locales/agreement/en.yml
  spec/requests/space/agreements_controller_request_spec.rb
Labels: ✨ enhancement, 🥔 Satisfices, 🥗 Nutritious

#1396 ✨ `Marketplace`: ask for missing delivery details to proceed to checkout
  app/furniture/marketplace/cart.rb
  app/furniture/marketplace/cart/deliveries/_delivery.html.erb
  app/furniture/marketplace/cart/deliveries/_form.html.erb
  app/furniture/marketplace/cart/deliveries_controller.rb
  app/furniture/marketplace/carts/_footer.html.erb
  app/furniture/marketplace/delivery.rb
  app/furniture/marketplace/locales/en.yml
  app/furniture/marketplace/marketplaces/_marketplace.html.erb
  spec/furniture/marketplace/cart/deliveries_controller_request_spec.rb
Labels: ✨ enhancement

#1412 🧹 `Marketplace`: Rename `marketplace_cart#delivery_window` to `delivery_notes`
  app/furniture/marketplace/cart.rb
  app/furniture/marketplace/cart/deliveries/_form.html.erb
  app/furniture/marketplace/cart/delivery.rb
  app/furniture/marketplace/cart/delivery_policy.rb
  app/furniture/marketplace/delivery.rb
  app/furniture/marketplace/delivery_area.rb
  app/furniture/marketplace/marketplaces/_marketplace.html.erb
  app/furniture/marketplace/order.rb
  app/furniture/marketplace/order/email_receipt_component.html.erb
  db/migrate/20230427003441_rename_marketplace_orders_delivery_window.rb
  db/schema.rb
  spec/factories/furniture/marketplace.rb
  spec/furniture/marketplace/cart/deliveries_controller_request_spec.rb
  spec/furniture/marketplace/cart/delivery_expectations_component_spec.rb
  spec/furniture/marketplace/cart/delivery_policy_spec.rb
  spec/furniture/marketplace/cart/delivery_spec.rb
  spec/furniture/marketplace/delivery_areas_controller_request_spec.rb
  spec/furniture/marketplace/delivery_spec.rb
  spec/furniture/marketplace/order/email_receipt_component_spec.rb
Labels: 🧹 refactor
