Repository zinc-collective/convene, pull requests merged in 2024-01, with the labels that each got.

#2080 Remove redundant edit icon from site footer
  app/views/layouts/application.html.erb
Labels: 🌸 Polish

#2081 🐛🔨 `Section`: Shorten Factory Generated `Room#description`
  app/models/room.rb
  spec/factories/room.rb
Labels: 🐞 bug, 🔨 Squashed

#2149 🌸 `Marketplace`: `Product#hero_image` is always 16:9
  app/furniture/marketplace/product_component.rb
Labels: 🌸 Polish

#2156 🧹 `Marketplace`: `Cart` no longer uses TurboStreams
  app/furniture/marketplace/cart_products_controller.rb
  spec/furniture/marketplace/cart_products_controller_request_spec.rb
Labels: 🧹 refactor

#2157 🧹 `Marketplace`: Simplify changing `Product` quantities in `Cart`
  app/furniture/marketplace/cart_product.rb
  app/furniture/marketplace/cart_product/quantity_picker.rb
  app/furniture/marketplace/cart_product/quantity_pickers/_quantity_picker.html.erb
  app/furniture/marketplace/cart_product_component.html.erb
  app/furniture/marketplace/cart_product_component.rb
  app/furniture/marketplace/locales/en.yml
  spec/furniture/marketplace/buying_products_system_spec.rb
  spec/furniture/marketplace/cart_product_component_spec.rb
Labels: 🧹 refactor

#2160 🛠️ `Gizmos`: Gizmos that don't use S3 shouldn't fail w/o AWS
  .env.test.example
Labels: 🛠️ infrastructure

#2072 🌸 `Marketplace`: `Shopper` adds `Product` to `Cart` through `Menu`
  app/furniture/marketplace/cart_product_component.html.erb
  app/furniture/marketplace/cart_product_component.rb
  app/furniture/marketplace/carts/_cart.html.erb
  app/furniture/marketplace/marketplace_component.html.erb
  app/furniture/marketplace/menu/product_component.html.erb
  app/furniture/marketplace/menu/product_component.rb
  app/furniture/marketplace/menu_component.html.erb
  app/furniture/marketplace/menu_component.rb
  spec/furniture/marketplace/buying_products_system_spec.rb
Labels: 🌸 Polish
