Repository zinc-collective/convene, pull requests merged in 2024-02, with the labels that each got.

#2171 ✨🥡 `Marketplace`: Add `Product#servings`
  app/furniture/marketplace/menu/product_component.html.erb
  app/furniture/marketplace/product/title_component.html.erb
  app/furniture/marketplace/product/title_component.rb
  app/furniture/marketplace/product_component.html.erb
  app/furniture/marketplace/product_policy.rb
  app/furniture/marketplace/products/_form.html.erb
  db/migrate/20240201014607_marketplace_add_servings_to_products.rb
  db/schema.rb
  spec/furniture/marketplace/selling_products_system_spec.rb
Labels: ✨ feature, 🥗 test automation

#2161 ✨ `Journal`: `Author` provides `Entry#summary`
  .github/workflows/test-convene-journal.yml
  app/furniture/journal/entries/_form.html.erb
  app/furniture/journal/entry.rb
  app/furniture/journal/entry_policy.rb
  db/migrate/20240129014151_journal_add_description_to_entry.rb
  db/schema.rb
  spec/furniture/journal/entry_spec.rb
  spec/furniture/journal/writing_entries_system_spec.rb
Labels: ✨ feature

#2164 🧹 `Section`: Manage `Section#hero_image` as an independent Resource
  app/controllers/room/hero_images_controller.rb
  app/controllers/rooms_controller.rb
  app/lib/space_routes.rb
  app/views/rooms/_form.html.erb
  app/views/rooms/edit.html.erb
  app/views/rooms/hero_image/_form.html.erb
  config/locales/room/en.yml
  config/locales/room/images/en.yml
  db/schema.rb
  spec/requests/room/hero_images_controller_request_spec.rb
Labels: 🧹 refactor

#2199 🐞🔨`Marketplace`: `Buying Products` with one unarchived `DeliveryArea`
  app/furniture/marketplace/carts/_footer.html.erb
  app/furniture/marketplace/marketplace.rb
  spec/furniture/marketplace/buying_products_system_spec.rb
  spec/furniture/marketplace/marketplace_spec.rb
Labels: 🐞 bug, 🔨 Squashed

#2188 🌸✨ `SectionNavigation` and `Section`: Show `Section#hero_image`
  app/components/card_component.html.erb
  app/components/card_component.rb
  app/furniture/marketplace/marketplace_component.html.erb
  app/furniture/marketplace/product_component.rb
  app/furniture/section_navigation/section_navigations/_section_navigation.html.erb
  app/models/media.rb
  app/views/furnitures/_furniture.html.erb
  app/views/rooms/_room.html.erb
Labels: ✨ feature, 🌸 Polish

#2211 ⚙️ `Gizmos`: Support `ActionText`
  app/assets/stylesheets/actiontext.css
  app/assets/stylesheets/application.postcss.css
  app/javascript/application.js
  app/views/active_storage/blobs/_blob.html.erb
  app/views/layouts/action_text/contents/_content.html.erb
  db/migrate/20240216213129_create_action_text_tables.action_text.rb
  db/schema.rb
  package.json
  spec/rails_helper.rb
  spec/spec_helper.rb
  yarn.lock
Labels: 🗜️ Gizmos, 🛠️ infrastructure

#2200 🌸✨🥡 `Marketplace`: `Products#description` is Rich Text
  app/assets/stylesheets/application.postcss.css
  app/furniture/marketplace/cart_product_component.html.erb
  app/furniture/marketplace/menu_component.html.erb
  app/furniture/marketplace/product.rb
  app/furniture/marketplace/products/_form.html.erb
  app/furniture/marketplace/products_controller.rb
  app/views/application/_rich_text_area.html.erb
  lib/tasks/release.rake
  spec/furniture/marketplace/cart_product_component_spec.rb
  spec/furniture/marketplace/menu/product_component_spec.rb
  spec/furniture/marketplace/product_component_spec.rb
  spec/furniture/marketplace/products_controller_request_spec.rb
  spec/furniture/marketplace/selling_products_system_spec.rb
Labels: ✨ feature, 🥗 test automation, 🌸 Polish

#2238 🧹 `Marketplace`: Remove `Product#description` column
  app/furniture/marketplace/product.rb
  db/migrate/20240222004148_remove_marketplace_products_description.rb
  db/schema.rb
  lib/tasks/release.rake
Labels: 🧹 refactor
